# Generated by Django 3.1.4 on 2021-03-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300, null=True)),
                ('words_count', models.IntegerField(null=True)),
                ('http_status_code', models.IntegerField(null=True)),
                ('about_error', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300, null=True)),
                ('timestamp', models.DateTimeField()),
                ('http_status', models.IntegerField(default=200)),
                ('task_status', models.PositiveBigIntegerField(choices=[(1, 'NOT_STARTED'), (2, 'PENDING'), (3, 'FINISHED')], default=1)),
            ],
        ),
    ]
